/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ciir.proteus;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Coordinates implements org.apache.thrift.TBase<Coordinates, Coordinates._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Coordinates");

  private static final org.apache.thrift.protocol.TField LEFT_FIELD_DESC = new org.apache.thrift.protocol.TField("left", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField RIGHT_FIELD_DESC = new org.apache.thrift.protocol.TField("right", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField TOP_FIELD_DESC = new org.apache.thrift.protocol.TField("top", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField BOTTOM_FIELD_DESC = new org.apache.thrift.protocol.TField("bottom", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CoordinatesStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CoordinatesTupleSchemeFactory());
  }

  public int left; // required
  public int right; // required
  public int top; // required
  public int bottom; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LEFT((short)1, "left"),
    RIGHT((short)2, "right"),
    TOP((short)3, "top"),
    BOTTOM((short)4, "bottom");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LEFT
          return LEFT;
        case 2: // RIGHT
          return RIGHT;
        case 3: // TOP
          return TOP;
        case 4: // BOTTOM
          return BOTTOM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LEFT_ISSET_ID = 0;
  private static final int __RIGHT_ISSET_ID = 1;
  private static final int __TOP_ISSET_ID = 2;
  private static final int __BOTTOM_ISSET_ID = 3;
  private BitSet __isset_bit_vector = new BitSet(4);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LEFT, new org.apache.thrift.meta_data.FieldMetaData("left", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.RIGHT, new org.apache.thrift.meta_data.FieldMetaData("right", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TOP, new org.apache.thrift.meta_data.FieldMetaData("top", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.BOTTOM, new org.apache.thrift.meta_data.FieldMetaData("bottom", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Coordinates.class, metaDataMap);
  }

  public Coordinates() {
  }

  public Coordinates(
    int left,
    int right,
    int top,
    int bottom)
  {
    this();
    this.left = left;
    setLeftIsSet(true);
    this.right = right;
    setRightIsSet(true);
    this.top = top;
    setTopIsSet(true);
    this.bottom = bottom;
    setBottomIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Coordinates(Coordinates other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.left = other.left;
    this.right = other.right;
    this.top = other.top;
    this.bottom = other.bottom;
  }

  public Coordinates deepCopy() {
    return new Coordinates(this);
  }

  @Override
  public void clear() {
    setLeftIsSet(false);
    this.left = 0;
    setRightIsSet(false);
    this.right = 0;
    setTopIsSet(false);
    this.top = 0;
    setBottomIsSet(false);
    this.bottom = 0;
  }

  public int getLeft() {
    return this.left;
  }

  public Coordinates setLeft(int left) {
    this.left = left;
    setLeftIsSet(true);
    return this;
  }

  public void unsetLeft() {
    __isset_bit_vector.clear(__LEFT_ISSET_ID);
  }

  /** Returns true if field left is set (has been assigned a value) and false otherwise */
  public boolean isSetLeft() {
    return __isset_bit_vector.get(__LEFT_ISSET_ID);
  }

  public void setLeftIsSet(boolean value) {
    __isset_bit_vector.set(__LEFT_ISSET_ID, value);
  }

  public int getRight() {
    return this.right;
  }

  public Coordinates setRight(int right) {
    this.right = right;
    setRightIsSet(true);
    return this;
  }

  public void unsetRight() {
    __isset_bit_vector.clear(__RIGHT_ISSET_ID);
  }

  /** Returns true if field right is set (has been assigned a value) and false otherwise */
  public boolean isSetRight() {
    return __isset_bit_vector.get(__RIGHT_ISSET_ID);
  }

  public void setRightIsSet(boolean value) {
    __isset_bit_vector.set(__RIGHT_ISSET_ID, value);
  }

  public int getTop() {
    return this.top;
  }

  public Coordinates setTop(int top) {
    this.top = top;
    setTopIsSet(true);
    return this;
  }

  public void unsetTop() {
    __isset_bit_vector.clear(__TOP_ISSET_ID);
  }

  /** Returns true if field top is set (has been assigned a value) and false otherwise */
  public boolean isSetTop() {
    return __isset_bit_vector.get(__TOP_ISSET_ID);
  }

  public void setTopIsSet(boolean value) {
    __isset_bit_vector.set(__TOP_ISSET_ID, value);
  }

  public int getBottom() {
    return this.bottom;
  }

  public Coordinates setBottom(int bottom) {
    this.bottom = bottom;
    setBottomIsSet(true);
    return this;
  }

  public void unsetBottom() {
    __isset_bit_vector.clear(__BOTTOM_ISSET_ID);
  }

  /** Returns true if field bottom is set (has been assigned a value) and false otherwise */
  public boolean isSetBottom() {
    return __isset_bit_vector.get(__BOTTOM_ISSET_ID);
  }

  public void setBottomIsSet(boolean value) {
    __isset_bit_vector.set(__BOTTOM_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LEFT:
      if (value == null) {
        unsetLeft();
      } else {
        setLeft((Integer)value);
      }
      break;

    case RIGHT:
      if (value == null) {
        unsetRight();
      } else {
        setRight((Integer)value);
      }
      break;

    case TOP:
      if (value == null) {
        unsetTop();
      } else {
        setTop((Integer)value);
      }
      break;

    case BOTTOM:
      if (value == null) {
        unsetBottom();
      } else {
        setBottom((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LEFT:
      return Integer.valueOf(getLeft());

    case RIGHT:
      return Integer.valueOf(getRight());

    case TOP:
      return Integer.valueOf(getTop());

    case BOTTOM:
      return Integer.valueOf(getBottom());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LEFT:
      return isSetLeft();
    case RIGHT:
      return isSetRight();
    case TOP:
      return isSetTop();
    case BOTTOM:
      return isSetBottom();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Coordinates)
      return this.equals((Coordinates)that);
    return false;
  }

  public boolean equals(Coordinates that) {
    if (that == null)
      return false;

    boolean this_present_left = true;
    boolean that_present_left = true;
    if (this_present_left || that_present_left) {
      if (!(this_present_left && that_present_left))
        return false;
      if (this.left != that.left)
        return false;
    }

    boolean this_present_right = true;
    boolean that_present_right = true;
    if (this_present_right || that_present_right) {
      if (!(this_present_right && that_present_right))
        return false;
      if (this.right != that.right)
        return false;
    }

    boolean this_present_top = true;
    boolean that_present_top = true;
    if (this_present_top || that_present_top) {
      if (!(this_present_top && that_present_top))
        return false;
      if (this.top != that.top)
        return false;
    }

    boolean this_present_bottom = true;
    boolean that_present_bottom = true;
    if (this_present_bottom || that_present_bottom) {
      if (!(this_present_bottom && that_present_bottom))
        return false;
      if (this.bottom != that.bottom)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Coordinates other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Coordinates typedOther = (Coordinates)other;

    lastComparison = Boolean.valueOf(isSetLeft()).compareTo(typedOther.isSetLeft());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLeft()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.left, typedOther.left);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRight()).compareTo(typedOther.isSetRight());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRight()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.right, typedOther.right);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTop()).compareTo(typedOther.isSetTop());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTop()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.top, typedOther.top);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBottom()).compareTo(typedOther.isSetBottom());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBottom()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bottom, typedOther.bottom);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Coordinates(");
    boolean first = true;

    sb.append("left:");
    sb.append(this.left);
    first = false;
    if (!first) sb.append(", ");
    sb.append("right:");
    sb.append(this.right);
    first = false;
    if (!first) sb.append(", ");
    sb.append("top:");
    sb.append(this.top);
    first = false;
    if (!first) sb.append(", ");
    sb.append("bottom:");
    sb.append(this.bottom);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CoordinatesStandardSchemeFactory implements SchemeFactory {
    public CoordinatesStandardScheme getScheme() {
      return new CoordinatesStandardScheme();
    }
  }

  private static class CoordinatesStandardScheme extends StandardScheme<Coordinates> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Coordinates struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LEFT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.left = iprot.readI32();
              struct.setLeftIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RIGHT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.right = iprot.readI32();
              struct.setRightIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TOP
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.top = iprot.readI32();
              struct.setTopIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // BOTTOM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.bottom = iprot.readI32();
              struct.setBottomIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Coordinates struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(LEFT_FIELD_DESC);
      oprot.writeI32(struct.left);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RIGHT_FIELD_DESC);
      oprot.writeI32(struct.right);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TOP_FIELD_DESC);
      oprot.writeI32(struct.top);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BOTTOM_FIELD_DESC);
      oprot.writeI32(struct.bottom);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CoordinatesTupleSchemeFactory implements SchemeFactory {
    public CoordinatesTupleScheme getScheme() {
      return new CoordinatesTupleScheme();
    }
  }

  private static class CoordinatesTupleScheme extends TupleScheme<Coordinates> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Coordinates struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetLeft()) {
        optionals.set(0);
      }
      if (struct.isSetRight()) {
        optionals.set(1);
      }
      if (struct.isSetTop()) {
        optionals.set(2);
      }
      if (struct.isSetBottom()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetLeft()) {
        oprot.writeI32(struct.left);
      }
      if (struct.isSetRight()) {
        oprot.writeI32(struct.right);
      }
      if (struct.isSetTop()) {
        oprot.writeI32(struct.top);
      }
      if (struct.isSetBottom()) {
        oprot.writeI32(struct.bottom);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Coordinates struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.left = iprot.readI32();
        struct.setLeftIsSet(true);
      }
      if (incoming.get(1)) {
        struct.right = iprot.readI32();
        struct.setRightIsSet(true);
      }
      if (incoming.get(2)) {
        struct.top = iprot.readI32();
        struct.setTopIsSet(true);
      }
      if (incoming.get(3)) {
        struct.bottom = iprot.readI32();
        struct.setBottomIsSet(true);
      }
    }
  }

}

