/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ciir.proteus;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Picture implements org.apache.thrift.TBase<Picture, Picture._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Picture");

  private static final org.apache.thrift.protocol.TField CAPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("caption", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField COORDINATES_FIELD_DESC = new org.apache.thrift.protocol.TField("coordinates", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField CREATORS_FIELD_DESC = new org.apache.thrift.protocol.TField("creators", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PictureStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PictureTupleSchemeFactory());
  }

  public String caption; // optional
  public Coordinates coordinates; // optional
  public List<String> creators; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CAPTION((short)1, "caption"),
    COORDINATES((short)2, "coordinates"),
    CREATORS((short)3, "creators");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CAPTION
          return CAPTION;
        case 2: // COORDINATES
          return COORDINATES;
        case 3: // CREATORS
          return CREATORS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.CAPTION,_Fields.COORDINATES};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CAPTION, new org.apache.thrift.meta_data.FieldMetaData("caption", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.COORDINATES, new org.apache.thrift.meta_data.FieldMetaData("coordinates", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Coordinates.class)));
    tmpMap.put(_Fields.CREATORS, new org.apache.thrift.meta_data.FieldMetaData("creators", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Picture.class, metaDataMap);
  }

  public Picture() {
  }

  public Picture(
    List<String> creators)
  {
    this();
    this.creators = creators;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Picture(Picture other) {
    if (other.isSetCaption()) {
      this.caption = other.caption;
    }
    if (other.isSetCoordinates()) {
      this.coordinates = new Coordinates(other.coordinates);
    }
    if (other.isSetCreators()) {
      List<String> __this__creators = new ArrayList<String>();
      for (String other_element : other.creators) {
        __this__creators.add(other_element);
      }
      this.creators = __this__creators;
    }
  }

  public Picture deepCopy() {
    return new Picture(this);
  }

  @Override
  public void clear() {
    this.caption = null;
    this.coordinates = null;
    this.creators = null;
  }

  public String getCaption() {
    return this.caption;
  }

  public Picture setCaption(String caption) {
    this.caption = caption;
    return this;
  }

  public void unsetCaption() {
    this.caption = null;
  }

  /** Returns true if field caption is set (has been assigned a value) and false otherwise */
  public boolean isSetCaption() {
    return this.caption != null;
  }

  public void setCaptionIsSet(boolean value) {
    if (!value) {
      this.caption = null;
    }
  }

  public Coordinates getCoordinates() {
    return this.coordinates;
  }

  public Picture setCoordinates(Coordinates coordinates) {
    this.coordinates = coordinates;
    return this;
  }

  public void unsetCoordinates() {
    this.coordinates = null;
  }

  /** Returns true if field coordinates is set (has been assigned a value) and false otherwise */
  public boolean isSetCoordinates() {
    return this.coordinates != null;
  }

  public void setCoordinatesIsSet(boolean value) {
    if (!value) {
      this.coordinates = null;
    }
  }

  public int getCreatorsSize() {
    return (this.creators == null) ? 0 : this.creators.size();
  }

  public java.util.Iterator<String> getCreatorsIterator() {
    return (this.creators == null) ? null : this.creators.iterator();
  }

  public void addToCreators(String elem) {
    if (this.creators == null) {
      this.creators = new ArrayList<String>();
    }
    this.creators.add(elem);
  }

  public List<String> getCreators() {
    return this.creators;
  }

  public Picture setCreators(List<String> creators) {
    this.creators = creators;
    return this;
  }

  public void unsetCreators() {
    this.creators = null;
  }

  /** Returns true if field creators is set (has been assigned a value) and false otherwise */
  public boolean isSetCreators() {
    return this.creators != null;
  }

  public void setCreatorsIsSet(boolean value) {
    if (!value) {
      this.creators = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CAPTION:
      if (value == null) {
        unsetCaption();
      } else {
        setCaption((String)value);
      }
      break;

    case COORDINATES:
      if (value == null) {
        unsetCoordinates();
      } else {
        setCoordinates((Coordinates)value);
      }
      break;

    case CREATORS:
      if (value == null) {
        unsetCreators();
      } else {
        setCreators((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CAPTION:
      return getCaption();

    case COORDINATES:
      return getCoordinates();

    case CREATORS:
      return getCreators();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CAPTION:
      return isSetCaption();
    case COORDINATES:
      return isSetCoordinates();
    case CREATORS:
      return isSetCreators();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Picture)
      return this.equals((Picture)that);
    return false;
  }

  public boolean equals(Picture that) {
    if (that == null)
      return false;

    boolean this_present_caption = true && this.isSetCaption();
    boolean that_present_caption = true && that.isSetCaption();
    if (this_present_caption || that_present_caption) {
      if (!(this_present_caption && that_present_caption))
        return false;
      if (!this.caption.equals(that.caption))
        return false;
    }

    boolean this_present_coordinates = true && this.isSetCoordinates();
    boolean that_present_coordinates = true && that.isSetCoordinates();
    if (this_present_coordinates || that_present_coordinates) {
      if (!(this_present_coordinates && that_present_coordinates))
        return false;
      if (!this.coordinates.equals(that.coordinates))
        return false;
    }

    boolean this_present_creators = true && this.isSetCreators();
    boolean that_present_creators = true && that.isSetCreators();
    if (this_present_creators || that_present_creators) {
      if (!(this_present_creators && that_present_creators))
        return false;
      if (!this.creators.equals(that.creators))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Picture other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Picture typedOther = (Picture)other;

    lastComparison = Boolean.valueOf(isSetCaption()).compareTo(typedOther.isSetCaption());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCaption()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.caption, typedOther.caption);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCoordinates()).compareTo(typedOther.isSetCoordinates());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCoordinates()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.coordinates, typedOther.coordinates);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreators()).compareTo(typedOther.isSetCreators());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreators()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.creators, typedOther.creators);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Picture(");
    boolean first = true;

    if (isSetCaption()) {
      sb.append("caption:");
      if (this.caption == null) {
        sb.append("null");
      } else {
        sb.append(this.caption);
      }
      first = false;
    }
    if (isSetCoordinates()) {
      if (!first) sb.append(", ");
      sb.append("coordinates:");
      if (this.coordinates == null) {
        sb.append("null");
      } else {
        sb.append(this.coordinates);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("creators:");
    if (this.creators == null) {
      sb.append("null");
    } else {
      sb.append(this.creators);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PictureStandardSchemeFactory implements SchemeFactory {
    public PictureStandardScheme getScheme() {
      return new PictureStandardScheme();
    }
  }

  private static class PictureStandardScheme extends StandardScheme<Picture> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Picture struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CAPTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.caption = iprot.readString();
              struct.setCaptionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COORDINATES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.coordinates = new Coordinates();
              struct.coordinates.read(iprot);
              struct.setCoordinatesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CREATORS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list98 = iprot.readListBegin();
                struct.creators = new ArrayList<String>(_list98.size);
                for (int _i99 = 0; _i99 < _list98.size; ++_i99)
                {
                  String _elem100; // optional
                  _elem100 = iprot.readString();
                  struct.creators.add(_elem100);
                }
                iprot.readListEnd();
              }
              struct.setCreatorsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Picture struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.caption != null) {
        if (struct.isSetCaption()) {
          oprot.writeFieldBegin(CAPTION_FIELD_DESC);
          oprot.writeString(struct.caption);
          oprot.writeFieldEnd();
        }
      }
      if (struct.coordinates != null) {
        if (struct.isSetCoordinates()) {
          oprot.writeFieldBegin(COORDINATES_FIELD_DESC);
          struct.coordinates.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.creators != null) {
        oprot.writeFieldBegin(CREATORS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.creators.size()));
          for (String _iter101 : struct.creators)
          {
            oprot.writeString(_iter101);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PictureTupleSchemeFactory implements SchemeFactory {
    public PictureTupleScheme getScheme() {
      return new PictureTupleScheme();
    }
  }

  private static class PictureTupleScheme extends TupleScheme<Picture> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Picture struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCaption()) {
        optionals.set(0);
      }
      if (struct.isSetCoordinates()) {
        optionals.set(1);
      }
      if (struct.isSetCreators()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetCaption()) {
        oprot.writeString(struct.caption);
      }
      if (struct.isSetCoordinates()) {
        struct.coordinates.write(oprot);
      }
      if (struct.isSetCreators()) {
        {
          oprot.writeI32(struct.creators.size());
          for (String _iter102 : struct.creators)
          {
            oprot.writeString(_iter102);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Picture struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.caption = iprot.readString();
        struct.setCaptionIsSet(true);
      }
      if (incoming.get(1)) {
        struct.coordinates = new Coordinates();
        struct.coordinates.read(iprot);
        struct.setCoordinatesIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list103 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.creators = new ArrayList<String>(_list103.size);
          for (int _i104 = 0; _i104 < _list103.size; ++_i104)
          {
            String _elem105; // optional
            _elem105 = iprot.readString();
            struct.creators.add(_elem105);
          }
        }
        struct.setCreatorsIsSet(true);
      }
    }
  }

}

