/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ciir.proteus;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TransformType implements org.apache.thrift.TEnum {
  TO_CONTAINER(0),
  TO_CONTENTS(1),
  OVERLAP(2),
  OBJECT_OF(3),
  SUBJECT_OF(4),
  HAS_AS_OBJECT(5),
  HAS_AS_SUBJECT(6),
  GEOGRAPHIC_PROX(7);

  private final int value;

  private TransformType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TransformType findByValue(int value) { 
    switch (value) {
      case 0:
        return TO_CONTAINER;
      case 1:
        return TO_CONTENTS;
      case 2:
        return OVERLAP;
      case 3:
        return OBJECT_OF;
      case 4:
        return SUBJECT_OF;
      case 5:
        return HAS_AS_OBJECT;
      case 6:
        return HAS_AS_SUBJECT;
      case 7:
        return GEOGRAPHIC_PROX;
      default:
        return null;
    }
  }
}
