/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ciir.proteus.galago.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Page implements org.apache.thrift.TBase<Page, Page._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Page");

  private static final org.apache.thrift.protocol.TField FULL_TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("full_text", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CREATORS_FIELD_DESC = new org.apache.thrift.protocol.TField("creators", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField PAGE_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("page_number", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PageStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PageTupleSchemeFactory());
  }

  public String full_text; // optional
  public List<String> creators; // required
  public int page_number; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FULL_TEXT((short)1, "full_text"),
    CREATORS((short)2, "creators"),
    PAGE_NUMBER((short)3, "page_number");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FULL_TEXT
          return FULL_TEXT;
        case 2: // CREATORS
          return CREATORS;
        case 3: // PAGE_NUMBER
          return PAGE_NUMBER;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PAGE_NUMBER_ISSET_ID = 0;
  private BitSet __isset_bit_vector = new BitSet(1);
  private _Fields optionals[] = {_Fields.FULL_TEXT,_Fields.PAGE_NUMBER};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FULL_TEXT, new org.apache.thrift.meta_data.FieldMetaData("full_text", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CREATORS, new org.apache.thrift.meta_data.FieldMetaData("creators", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.PAGE_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("page_number", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Page.class, metaDataMap);
  }

  public Page() {
  }

  public Page(
    List<String> creators)
  {
    this();
    this.creators = creators;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Page(Page other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetFull_text()) {
      this.full_text = other.full_text;
    }
    if (other.isSetCreators()) {
      List<String> __this__creators = new ArrayList<String>();
      for (String other_element : other.creators) {
        __this__creators.add(other_element);
      }
      this.creators = __this__creators;
    }
    this.page_number = other.page_number;
  }

  public Page deepCopy() {
    return new Page(this);
  }

  @Override
  public void clear() {
    this.full_text = null;
    this.creators = null;
    setPage_numberIsSet(false);
    this.page_number = 0;
  }

  public String getFull_text() {
    return this.full_text;
  }

  public Page setFull_text(String full_text) {
    this.full_text = full_text;
    return this;
  }

  public void unsetFull_text() {
    this.full_text = null;
  }

  /** Returns true if field full_text is set (has been assigned a value) and false otherwise */
  public boolean isSetFull_text() {
    return this.full_text != null;
  }

  public void setFull_textIsSet(boolean value) {
    if (!value) {
      this.full_text = null;
    }
  }

  public int getCreatorsSize() {
    return (this.creators == null) ? 0 : this.creators.size();
  }

  public java.util.Iterator<String> getCreatorsIterator() {
    return (this.creators == null) ? null : this.creators.iterator();
  }

  public void addToCreators(String elem) {
    if (this.creators == null) {
      this.creators = new ArrayList<String>();
    }
    this.creators.add(elem);
  }

  public List<String> getCreators() {
    return this.creators;
  }

  public Page setCreators(List<String> creators) {
    this.creators = creators;
    return this;
  }

  public void unsetCreators() {
    this.creators = null;
  }

  /** Returns true if field creators is set (has been assigned a value) and false otherwise */
  public boolean isSetCreators() {
    return this.creators != null;
  }

  public void setCreatorsIsSet(boolean value) {
    if (!value) {
      this.creators = null;
    }
  }

  public int getPage_number() {
    return this.page_number;
  }

  public Page setPage_number(int page_number) {
    this.page_number = page_number;
    setPage_numberIsSet(true);
    return this;
  }

  public void unsetPage_number() {
    __isset_bit_vector.clear(__PAGE_NUMBER_ISSET_ID);
  }

  /** Returns true if field page_number is set (has been assigned a value) and false otherwise */
  public boolean isSetPage_number() {
    return __isset_bit_vector.get(__PAGE_NUMBER_ISSET_ID);
  }

  public void setPage_numberIsSet(boolean value) {
    __isset_bit_vector.set(__PAGE_NUMBER_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FULL_TEXT:
      if (value == null) {
        unsetFull_text();
      } else {
        setFull_text((String)value);
      }
      break;

    case CREATORS:
      if (value == null) {
        unsetCreators();
      } else {
        setCreators((List<String>)value);
      }
      break;

    case PAGE_NUMBER:
      if (value == null) {
        unsetPage_number();
      } else {
        setPage_number((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FULL_TEXT:
      return getFull_text();

    case CREATORS:
      return getCreators();

    case PAGE_NUMBER:
      return Integer.valueOf(getPage_number());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FULL_TEXT:
      return isSetFull_text();
    case CREATORS:
      return isSetCreators();
    case PAGE_NUMBER:
      return isSetPage_number();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Page)
      return this.equals((Page)that);
    return false;
  }

  public boolean equals(Page that) {
    if (that == null)
      return false;

    boolean this_present_full_text = true && this.isSetFull_text();
    boolean that_present_full_text = true && that.isSetFull_text();
    if (this_present_full_text || that_present_full_text) {
      if (!(this_present_full_text && that_present_full_text))
        return false;
      if (!this.full_text.equals(that.full_text))
        return false;
    }

    boolean this_present_creators = true && this.isSetCreators();
    boolean that_present_creators = true && that.isSetCreators();
    if (this_present_creators || that_present_creators) {
      if (!(this_present_creators && that_present_creators))
        return false;
      if (!this.creators.equals(that.creators))
        return false;
    }

    boolean this_present_page_number = true && this.isSetPage_number();
    boolean that_present_page_number = true && that.isSetPage_number();
    if (this_present_page_number || that_present_page_number) {
      if (!(this_present_page_number && that_present_page_number))
        return false;
      if (this.page_number != that.page_number)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Page other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Page typedOther = (Page)other;

    lastComparison = Boolean.valueOf(isSetFull_text()).compareTo(typedOther.isSetFull_text());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFull_text()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.full_text, typedOther.full_text);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreators()).compareTo(typedOther.isSetCreators());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreators()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.creators, typedOther.creators);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPage_number()).compareTo(typedOther.isSetPage_number());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPage_number()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.page_number, typedOther.page_number);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Page(");
    boolean first = true;

    if (isSetFull_text()) {
      sb.append("full_text:");
      if (this.full_text == null) {
        sb.append("null");
      } else {
        sb.append(this.full_text);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("creators:");
    if (this.creators == null) {
      sb.append("null");
    } else {
      sb.append(this.creators);
    }
    first = false;
    if (isSetPage_number()) {
      if (!first) sb.append(", ");
      sb.append("page_number:");
      sb.append(this.page_number);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PageStandardSchemeFactory implements SchemeFactory {
    public PageStandardScheme getScheme() {
      return new PageStandardScheme();
    }
  }

  private static class PageStandardScheme extends StandardScheme<Page> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Page struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FULL_TEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.full_text = iprot.readString();
              struct.setFull_textIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CREATORS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list82 = iprot.readListBegin();
                struct.creators = new ArrayList<String>(_list82.size);
                for (int _i83 = 0; _i83 < _list82.size; ++_i83)
                {
                  String _elem84; // optional
                  _elem84 = iprot.readString();
                  struct.creators.add(_elem84);
                }
                iprot.readListEnd();
              }
              struct.setCreatorsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PAGE_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.page_number = iprot.readI32();
              struct.setPage_numberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Page struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.full_text != null) {
        if (struct.isSetFull_text()) {
          oprot.writeFieldBegin(FULL_TEXT_FIELD_DESC);
          oprot.writeString(struct.full_text);
          oprot.writeFieldEnd();
        }
      }
      if (struct.creators != null) {
        oprot.writeFieldBegin(CREATORS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.creators.size()));
          for (String _iter85 : struct.creators)
          {
            oprot.writeString(_iter85);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.isSetPage_number()) {
        oprot.writeFieldBegin(PAGE_NUMBER_FIELD_DESC);
        oprot.writeI32(struct.page_number);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PageTupleSchemeFactory implements SchemeFactory {
    public PageTupleScheme getScheme() {
      return new PageTupleScheme();
    }
  }

  private static class PageTupleScheme extends TupleScheme<Page> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Page struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFull_text()) {
        optionals.set(0);
      }
      if (struct.isSetCreators()) {
        optionals.set(1);
      }
      if (struct.isSetPage_number()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetFull_text()) {
        oprot.writeString(struct.full_text);
      }
      if (struct.isSetCreators()) {
        {
          oprot.writeI32(struct.creators.size());
          for (String _iter86 : struct.creators)
          {
            oprot.writeString(_iter86);
          }
        }
      }
      if (struct.isSetPage_number()) {
        oprot.writeI32(struct.page_number);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Page struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.full_text = iprot.readString();
        struct.setFull_textIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list87 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.creators = new ArrayList<String>(_list87.size);
          for (int _i88 = 0; _i88 < _list87.size; ++_i88)
          {
            String _elem89; // optional
            _elem89 = iprot.readString();
            struct.creators.add(_elem89);
          }
        }
        struct.setCreatorsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.page_number = iprot.readI32();
        struct.setPage_numberIsSet(true);
      }
    }
  }

}

