/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.lemurproject.galago.core.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PrefixedTermMap implements org.apache.thrift.TBase<PrefixedTermMap, PrefixedTermMap._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PrefixedTermMap");

  private static final org.apache.thrift.protocol.TField TERM_LISTS_FIELD_DESC = new org.apache.thrift.protocol.TField("term_lists", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PrefixedTermMapStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PrefixedTermMapTupleSchemeFactory());
  }

  public Map<String,TermList> term_lists; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TERM_LISTS((short)1, "term_lists");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TERM_LISTS
          return TERM_LISTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TERM_LISTS, new org.apache.thrift.meta_data.FieldMetaData("term_lists", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TermList.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PrefixedTermMap.class, metaDataMap);
  }

  public PrefixedTermMap() {
  }

  public PrefixedTermMap(
    Map<String,TermList> term_lists)
  {
    this();
    this.term_lists = term_lists;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PrefixedTermMap(PrefixedTermMap other) {
    if (other.isSetTerm_lists()) {
      Map<String,TermList> __this__term_lists = new HashMap<String,TermList>();
      for (Map.Entry<String, TermList> other_element : other.term_lists.entrySet()) {

        String other_element_key = other_element.getKey();
        TermList other_element_value = other_element.getValue();

        String __this__term_lists_copy_key = other_element_key;

        TermList __this__term_lists_copy_value = new TermList(other_element_value);

        __this__term_lists.put(__this__term_lists_copy_key, __this__term_lists_copy_value);
      }
      this.term_lists = __this__term_lists;
    }
  }

  public PrefixedTermMap deepCopy() {
    return new PrefixedTermMap(this);
  }

  @Override
  public void clear() {
    this.term_lists = null;
  }

  public int getTerm_listsSize() {
    return (this.term_lists == null) ? 0 : this.term_lists.size();
  }

  public void putToTerm_lists(String key, TermList val) {
    if (this.term_lists == null) {
      this.term_lists = new HashMap<String,TermList>();
    }
    this.term_lists.put(key, val);
  }

  public Map<String,TermList> getTerm_lists() {
    return this.term_lists;
  }

  public PrefixedTermMap setTerm_lists(Map<String,TermList> term_lists) {
    this.term_lists = term_lists;
    return this;
  }

  public void unsetTerm_lists() {
    this.term_lists = null;
  }

  /** Returns true if field term_lists is set (has been assigned a value) and false otherwise */
  public boolean isSetTerm_lists() {
    return this.term_lists != null;
  }

  public void setTerm_listsIsSet(boolean value) {
    if (!value) {
      this.term_lists = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TERM_LISTS:
      if (value == null) {
        unsetTerm_lists();
      } else {
        setTerm_lists((Map<String,TermList>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TERM_LISTS:
      return getTerm_lists();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TERM_LISTS:
      return isSetTerm_lists();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PrefixedTermMap)
      return this.equals((PrefixedTermMap)that);
    return false;
  }

  public boolean equals(PrefixedTermMap that) {
    if (that == null)
      return false;

    boolean this_present_term_lists = true && this.isSetTerm_lists();
    boolean that_present_term_lists = true && that.isSetTerm_lists();
    if (this_present_term_lists || that_present_term_lists) {
      if (!(this_present_term_lists && that_present_term_lists))
        return false;
      if (!this.term_lists.equals(that.term_lists))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(PrefixedTermMap other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    PrefixedTermMap typedOther = (PrefixedTermMap)other;

    lastComparison = Boolean.valueOf(isSetTerm_lists()).compareTo(typedOther.isSetTerm_lists());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTerm_lists()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.term_lists, typedOther.term_lists);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PrefixedTermMap(");
    boolean first = true;

    sb.append("term_lists:");
    if (this.term_lists == null) {
      sb.append("null");
    } else {
      sb.append(this.term_lists);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PrefixedTermMapStandardSchemeFactory implements SchemeFactory {
    public PrefixedTermMapStandardScheme getScheme() {
      return new PrefixedTermMapStandardScheme();
    }
  }

  private static class PrefixedTermMapStandardScheme extends StandardScheme<PrefixedTermMap> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PrefixedTermMap struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TERM_LISTS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map24 = iprot.readMapBegin();
                struct.term_lists = new HashMap<String,TermList>(2*_map24.size);
                for (int _i25 = 0; _i25 < _map24.size; ++_i25)
                {
                  String _key26; // required
                  TermList _val27; // required
                  _key26 = iprot.readString();
                  _val27 = new TermList();
                  _val27.read(iprot);
                  struct.term_lists.put(_key26, _val27);
                }
                iprot.readMapEnd();
              }
              struct.setTerm_listsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PrefixedTermMap struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.term_lists != null) {
        oprot.writeFieldBegin(TERM_LISTS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.term_lists.size()));
          for (Map.Entry<String, TermList> _iter28 : struct.term_lists.entrySet())
          {
            oprot.writeString(_iter28.getKey());
            _iter28.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PrefixedTermMapTupleSchemeFactory implements SchemeFactory {
    public PrefixedTermMapTupleScheme getScheme() {
      return new PrefixedTermMapTupleScheme();
    }
  }

  private static class PrefixedTermMapTupleScheme extends TupleScheme<PrefixedTermMap> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PrefixedTermMap struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTerm_lists()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTerm_lists()) {
        {
          oprot.writeI32(struct.term_lists.size());
          for (Map.Entry<String, TermList> _iter29 : struct.term_lists.entrySet())
          {
            oprot.writeString(_iter29.getKey());
            _iter29.getValue().write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PrefixedTermMap struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map30 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.term_lists = new HashMap<String,TermList>(2*_map30.size);
          for (int _i31 = 0; _i31 < _map30.size; ++_i31)
          {
            String _key32; // required
            TermList _val33; // required
            _key32 = iprot.readString();
            _val33 = new TermList();
            _val33.read(iprot);
            struct.term_lists.put(_key32, _val33);
          }
        }
        struct.setTerm_listsIsSet(true);
      }
    }
  }

}

